import { useEffect, useMemo, useState, type FormEvent } from 'react';
import { KeyRound } from 'lucide-react';
import { api, clearCSRFToken, setCSRFToken } from './api/client';
import { type WebSession } from './Auth';
import { errorMessage, safeReturnTo } from './authShared';
import { useTranslation } from 'react-i18next';

type SessionResponse = { ok: boolean; session: WebSession };

export default function CredentialUpdatePage() {
  const { t } = useTranslation();
  const params = useMemo(() => new URLSearchParams(window.location.search), []);
  const returnTo = safeReturnTo(params.get('return_to'));
  const [current, setCurrent] = useState('');
  const [next, setNext] = useState('');
  const [confirm, setConfirm] = useState('');
  const [session, setSession] = useState<WebSession | null>(null);
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState('');

  useEffect(() => {
    api<SessionResponse>('/v1/auth/session').then((result) => {
      setSession(result.session);
      if (result.session.csrf_token) setCSRFToken(result.session.csrf_token);
    }).catch(() => window.location.replace(`/login?return_to=${encodeURIComponent(returnTo)}`));
  }, [returnTo]);

  async function submit(event: FormEvent) {
    event.preventDefault();
    if (next !== confirm) {
      setError(t('The two new passwords do not match.'));
      return;
    }
    if (next.length < 12) {
      setError(t('The new password must be at least 12 characters.'));
      return;
    }
    setSubmitting(true);
    setError('');
    try {
      await api('/v1/auth/credential', { method: 'POST', body: JSON.stringify({ current, next }) });
      clearCSRFToken();
      window.location.replace(`/login?changed=1&return_to=${encodeURIComponent(returnTo)}`);
    } catch (submitError) {
      setError(errorMessage(submitError));
    } finally {
      setSubmitting(false);
    }
  }

  return (
    <main className="auth-shell">
      <section className="auth-panel">
        <form className="auth-card" aria-labelledby="credential-title" aria-busy={!session || submitting} onSubmit={submit}>
          <header><span className="auth-card-icon"><KeyRound size={21} /></span><div><h2 id="credential-title">{session?.must_change_password ? t('First sign-in security update') : t('Change administrator password')}</h2><p>{t('All browser sessions will be signed out immediately after the update')}</p></div></header>
          {error && <div id="credential-error" className="auth-error" role="alert">{error}</div>}
          <label htmlFor="credential-current"><span>{t('Current password')}</span><input id="credential-current" name="current_password" type="password" autoComplete="current-password" aria-invalid={Boolean(error)} aria-describedby={error ? 'credential-error' : undefined} value={current} onChange={(event) => setCurrent(event.target.value)} required /></label>
          <label htmlFor="credential-next"><span>{t('New password')}</span><input id="credential-next" name="new_password" type="password" autoComplete="new-password" aria-invalid={Boolean(error)} aria-describedby={error ? 'credential-policy credential-error' : 'credential-policy'} value={next} onChange={(event) => setNext(event.target.value)} minLength={12} required /></label>
          <label htmlFor="credential-confirm"><span>{t('Confirm new password')}</span><input id="credential-confirm" name="confirm_password" type="password" autoComplete="new-password" aria-invalid={Boolean(error)} aria-describedby={error ? 'credential-policy credential-error' : 'credential-policy'} value={confirm} onChange={(event) => setConfirm(event.target.value)} minLength={12} required /></label>
          <p id="credential-policy" className="auth-policy">{t('At least 12 characters; long passwords or passphrases generated by a password manager are supported.')}</p>
          <button className="auth-primary" type="submit" aria-busy={submitting} disabled={submitting || !session || !current || !next || !confirm}>{submitting ? t('Updating…') : t('Update and sign in again')}</button>
        </form>
      </section>
    </main>
  );
}
